onCreate:
  - printf "\nWelcome to RunCode.\n\nThis is a blank workspace with vscode browser."
  - printf "\nYou may change this content and automate as per your requirement"

onStart:
  - |
        printf "\nThe .runcode.yaml file will automate installations and configurations."
        printf "\nIt is having two parts, onCreate and onStart."
        printf "\nonCreate part will be executed first time when the workspace is launched."
        printf "\nonStart part will be executed every time when the workspace is launched."
        printf "\nFor Example: If you are developing a web application and want to see the output of the application running on local port 8000"
        printf "\nGO TO THIS URL TO VIEW PAGE \033[4;34m https://8000-${WS_DOMAIN}\033[0;30m\n\n"
